### PR TITLE
New ballot encoding algorithm

### PR DESCRIPTION
**Pull request by edulix**

### CODE REVIEW

**Comment by danigm** [comment]
@edulix, I've just added a commit removing some linting errors that appears when you run `grunt build`. Feel free to remove that commit if you're still working on that and want to do a cleanup later.

**Comment by edulix** [comment]
oh sure, thanks! sorry I didn't notice those.. probably I should improve my  VS Code config.

**Comment by edulix** [comment]
Looks like there are still some of those issues, right @danigm? maybe we should add a `grunt build` step to the github workflow so that they are more apparent. Here and in all the other agora-gui projects.

**Comment by edulix** [comment]
@danigm this is almost ready for merging, I'll do what I recommended creating a branch doing it in all those agora-gui repos related to this..

**Pull request merged**
